spring:
  application:
    name: saudacao-service"
  profiles:
    active:
      - pt
  config:
    import:
    - optional:configserver:http://localhost:8888
 
saudacao-service:
  saudacao: Hello
  nome-padrao: World