server:
  port: 8000
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost/produtos
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyaway:
    locations:
    - classpath:/db_migration