server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gabriel-Henrique-Gemelli/Microservices_java.git
          default-label: main
          search-paths:
          - 'configs/{application}'
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always